#!/bin/sh
set -e

user=testing

if [ $(id -u) = 0 ]
then
    adduser --quiet --system --group --no-create-home $user
    chown -R $user .
    runuser="runuser -p -u $user --"
else
    runuser=""
fi

for py in $(py3versions -s); do
	$runuser $py -m pytest flit_core
done

if [ $(id -u) = 0 ]
then
    deluser --quiet $user
fi
